version: "3.9"
services:
  db:
    container_name: pgsql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: laravel_test
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: hyre@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5000:80"